---
# tasks file for php
- 
  name: Install PHP 7 with the most common packages
  become: true
  state: present
  yum:
    - php70
    - php70-gd
    - php70-imap
    - php70-mbstring
    - php70-mysqlnd
    - php70-opcache
    - php70-pdo
    - php70-pecl-apcu
  notify: "restart Apache"
- name: Upload index.php file the remote server
  copy:
    src: index.php
    dest: /var/www/html
    owner: ec2-user
    group: ec2-user  
